import '../../core/utils/formatters.dart';
import '../../data/models/vehicle.dart';
import '../../data/models/tax_summary.dart';
import '../../data/models/trip.dart';
import 'evidence_engine.dart';

/// ATO-READY REPORT (Layer 6):
/// Generates official ATO TR 97/11 compliant audit records and Schedule D1 lodgement summaries.
class AtoReportService {
  /// Generates clean, accountant-ready CSV for lodgement and audits
  static String generateAtoAuditCsv({
    required Vehicle vehicle,
    required EvidenceEngine engine,
    required TaxSummary summary,
  }) {
    final buffer = StringBuffer();

    // 1. Audit Header Block
    buffer.writeln('========================================================================');
    buffer.writeln('OFFICIAL ATO MOTOR VEHICLE LOGBOOK & EXPENSE SCHEDULE (TR 97/11)');
    buffer.writeln('Generated by KiloTax • 100% Audit-Proof Local Evidence Engine');
    buffer.writeln('========================================================================');
    buffer.writeln('Vehicle Details: ${vehicle.displayName}');
    buffer.writeln('Registration: ${vehicle.regoPlate}');
    buffer.writeln('Initial Baseline Odometer: ${Formatters.odometer(vehicle.initialOdometer)} km');
    buffer.writeln('Statutory Business Percentage: ${Formatters.percentage(summary.businessPercentage)}');
    buffer.writeln('Recommended Lodgement Method: ${summary.recommendedMethod.displayName}');
    buffer.writeln('Eligible Tax Deduction (Box D1): ${Formatters.currency(summary.highestClaim)}');
    buffer.writeln('');

    // 2. Trips Schedule
    buffer.writeln('--- SCHEDULE 1: ATO MOTOR VEHICLE LOGBOOK TRIPS ---');
    buffer.writeln('Date,Origin,Destination,Purpose,Start Odo,End Odo,Distance (KM),Classification');
    for (final t in engine.trips) {
      final dateStr = t.date.toIso8601String().split('T').first;
      final origin = t.originAddress ?? 'Work Site';
      final dest = t.destinationAddress ?? 'Client Job';
      buffer.writeln('$dateStr,"$origin","$dest","${t.purpose}",${t.startOdometer},${t.endOdometer},${t.distanceKm},${t.classification.name.toUpperCase()}');
    }
    buffer.writeln('');

    // 3. Expenses Schedule
    buffer.writeln('--- SCHEDULE 2: ITEMIZED VEHICLE EXPENSES & SUBSTANTIATION ---');
    buffer.writeln('Date,Category,Amount (\$AUD),Business %,Deductible Claim,Receipt Attached');
    for (final e in engine.expenses) {
      final dateStr = e.date.toIso8601String().split('T').first;
      final hasReceipt = e.receiptPath != null && e.receiptPath!.isNotEmpty ? 'YES (Preserved)' : 'NO';
      final linkedTrip = e.linkedTripId != null ? engine.trips.cast<Trip?>().firstWhere((t) => t?.id == e.linkedTripId, orElse: () => null) : null;
      final tripDesc = linkedTrip != null ? '"Trip: ${linkedTrip.purpose} (${linkedTrip.distanceKm} km)"' : '"Stand-alone Running Cost"';
      final linkId = e.linkedTripId ?? 'DIRECT-CLAIM';
      buffer.writeln('$dateStr,"${e.category.displayName}",${e.amount.toStringAsFixed(2)},${Formatters.percentage(e.businessPercentage)},${e.deductibleAmount.toStringAsFixed(2)},$hasReceipt,$tripDesc,$linkId');
    }
    buffer.writeln('');

    // 4. Tax Agent Summary
    buffer.writeln('--- SCHEDULE 3: TAX AGENT RECONCILIATION SUMMARY ---');
    buffer.writeln('Total Distance Recorded: ${Formatters.distance(summary.totalKm)}');
    buffer.writeln('Total Business Distance: ${Formatters.distance(summary.businessKm)}');
    buffer.writeln('Cents-per-KM Calculated Claim: ${Formatters.currency(summary.centsPerKmClaim)}');
    buffer.writeln('Logbook Calculated Claim: ${Formatters.currency(summary.logbookClaim)}');
    buffer.writeln('Advised ATO Lodgement Figure: ${Formatters.currency(summary.highestClaim)}');

    return buffer.toString();
  }

  /// Generates a clean 1-Click summary message for the Tradie to WhatsApp or Email directly to their Accountant
  static String generateAccountantEmailText({
    required Vehicle vehicle,
    required TaxSummary summary,
    required int tripCount,
    required int expenseCount,
  }) {
    return '''Hi [Accountant Name],

Here is my official ATO Vehicle Tax Substantiation Summary for ${vehicle.displayName} (Rego: ${vehicle.regoPlate}) prepared via KiloTax.

--------------------------------------------------
📊 ATO TAX DEDUCTION CLAIM SUMMARY (FY2025-26):
--------------------------------------------------
• Primary Tax Method: ${summary.recommendedMethod.displayName}
• ATO Tax Return Box D1 Claim: ${Formatters.currency(summary.highestClaim)}
• Statutory Business Percentage: ${Formatters.percentage(summary.businessPercentage)}
• Total Distance Driven: ${Formatters.distance(summary.totalKm)}
• Total Business Work Distance: ${Formatters.distance(summary.businessKm)}

📁 ATTACHED AUDIT-PROOF EVIDENCE GRAPH:
• Total Logged Work Trips: $tripCount
• Total Substantiated Receipts: $expenseCount
• Continuous Odometer Baseline: ${Formatters.odometer(vehicle.initialOdometer)} km (Locked)

Full ATO TR 97/11 CSV log and cryptographic evidence vault are attached for direct import into Xero / MYOB.

Regards,
[Tradie Name]
''';
  }
}
